Layout/EmptyLineAfterMagicComment:
    Exclude:
        - 'db/schema.rb'

Layout/EmptyLinesAroundBlockBody:
    Exclude:
        - 'db/schema.rb'

Metrics/LineLength:
    Max: 150

Style/ClassAndModuleChildren:
    Exclude:
        - 'test/test_helper.rb'

Style/Documentation:
    Exclude:
        - 'app/helpers/application_helper.rb'
        - 'app/mailers/application_mailer.rb'
        - 'app/models/application_record.rb'
        - 'config/application.rb'
        - 'test/application_system_test_case.rb'
        - 'test/test_helper.rb'

Style/FrozenStringLiteralComment:
    Exclude:
        - 'db/schema.rb'

Style/MixinUsage:
    Exclude:
        - 'bin/setup'
        - 'bin/update'