AllCops:
    Exclude:
        - 'db/schema.rb'
        - 'vendor/**/*'

Metrics/AbcSize:
    Exclude:
        - 'db/migrate/*'
        - 'app/controllers/publications_controller.rb'
        - 'app/controllers/submitters_controller.rb'
        - 'spec/rails_helper.rb'

Metrics/BlockLength:
    Max: 125
    Exclude:
        - 'spec/controllers/submitters_controller_spec.rb'
        - 'spec/routing/submitters_routing_spec.rb'
        - 'spec/views/submitters/index.html.erb_spec.rb'

Metrics/MethodLength:
    Max: 20
    
Metrics/LineLength:
    Max: 275
    Exclude:
        - 'spec/controllers/*'

Style/ClassAndModuleChildren:
    Exclude:
        - 'test/test_helper.rb'

Style/Documentation:
    Exclude:
        - 'app/helpers/*'
        - 'app/controllers/*'
        - 'app/models/*'
        - 'db/**/*'
        - 'app/helpers/application_helper.rb'
        - 'app/mailers/application_mailer.rb'
        - 'app/models/application_record.rb'
        - 'config/application.rb'
        - 'test/application_system_test_case.rb'
        - 'test/test_helper.rb'
        - 'app/controllers/submitters_controller.rb'
        - 'app/helpers/submitters_helper.rb'
        - 'app/models/submitter.rb'

Style/MixinUsage:
    Exclude:
        - 'bin/setup'
        - 'bin/update'