AllCops:
    NewCops: enable
    Exclude:
        - 'db/schema.rb'
        - 'vendor/**/*'
            
Layout/LineLength:
    Max: 275
    Exclude:
        - 'spec/controllers/*'

Metrics/AbcSize:
    Exclude:
        - 'app/models/*'
        - 'db/migrate/*'
        - 'app/controllers/publications_controller.rb'
        - 'app/controllers/submitters_controller.rb'
        - 'app/helpers/colleges_helper.rb'
        - 'app/controllers/admin_controller.rb'
        - 'spec/rails_helper.rb'

Metrics/BlockLength:
    Max: 125
    Exclude:
        - 'spec/controllers/submitters_controller_spec.rb'
        - 'spec/routing/submitters_routing_spec.rb'
        - 'spec/views/submitters/index.html.erb_spec.rb'

Metrics/CyclomaticComplexity:
    Exclude:
        - 'app/controllers/publications_controller.rb'

Metrics/ClassLength:
    Max: 150

Metrics/MethodLength:
    Max: 100

Metrics/PerceivedComplexity:
    Exclude:
        - 'app/controllers/publications_controller.rb'

Style/ClassAndModuleChildren:
    Exclude:
        - 'test/test_helper.rb'

Style/Documentation:
    Exclude:
        - 'app/helpers/*'
        - 'app/controllers/*'
        - 'app/models/*'
        - 'db/**/*'
        - 'app/helpers/application_helper.rb'
        - 'app/mailers/*'
        - 'app/models/application_record.rb'
        - 'config/application.rb'
        - 'test/application_system_test_case.rb'
        - 'test/test_helper.rb'
        - 'app/controllers/submitters_controller.rb'
        - 'app/helpers/submitters_helper.rb'
        - 'app/models/submitter.rb'

Style/ExpandPathArguments:
    Exclude:
        - 'config/puma.rb'

Style/MixinUsage:
    Exclude:
        - 'bin/setup'
        - 'bin/update'
