version: "3.7"
services:
    aaec:
        command: bash -c "rails db:migrate && rails db:seed && cap deploy qa"
        # command: bash -c "rubocop -a && rspec"
        container_name: aaec
        image: aaec
        environment: 
            - SPROCKETS_CACHE=/cache
            - .:/aaec
        ports:
            - "3000:3000"
        stdin_open: true
        tty: true
        volumes:
            - .:/aaec
            - bundle:/bundle
            - cache:/cache
volumes:
    bundle:
    cache: